language: python
matrix:
  include:
    - python: "2.6"
      env: TOX_ENV=py26
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "pypy"
      env: TOX_ENV=pypy
    - python: "3.3"
      env: TOX_ENV=py33
    - python: "3.4"
      env: TOX_ENV=py34
install:
  # TODO(xion): extract requirements-ci.txt, referenced by requirements-dev
  - pip install tox>=1.7
script: tox -e $TOX_ENV
